gcc: 3336556d2cb32f46322922a83015f760cfb79d8f (2012-11-13; 6b7a0b5b7dfa4071c95418040cc0ee1528ba7915 (2012-08-05))

diff --git a/process b/process
--- a/process
+++ b/process
@@ -128,6 +128,26 @@ case $project:$action in
             find '"$branch$build_suffix"'.sums/ -type f \
               -exec sed -e "s%\('"$mount"'\)\?${PWD}%[...]%g" -i \{\} \;'
         case $project in
+          gcc)
+            # Rename host-specific directory to a generic name.
+            # This is probably not the most beautiful solution.
+            case $host in
+              "$linux_host")
+                arch=i686-pc-linux-gnu
+                ;;
+              "$hurd_host")
+                arch=i686-unknown-gnu0.3
+                ;;
+              *)
+                echo >&2 "Internal error."
+                exit 1
+                ;;
+            esac
+            ssh \
+              "$host" \
+                'cd '"$project_base"'/'"$branch$build_suffix"'.sums/ && \
+                mv '"$arch"' [ARCH]'
+            ;;
           gdb)
             # Remove the summary file; we got the individual ones.
             ssh \
