binutils-gdb: Re-run after system updates.

diff --git a/binutils-gdb/kepler.SCHWINGE/log_test b/binutils-gdb/kepler.SCHWINGE/log_test
--- a/binutils-gdb/kepler.SCHWINGE/log_test
+++ b/binutils-gdb/kepler.SCHWINGE/log_test
@@ -11,14 +11,12 @@ make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/bfd/po'
 make[4]: Nothing to be done for 'check'.
 make[4]: Leaving directory '[...]/tschwinge/W._C._Handy.build/bfd/po'
 make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/bfd'
-make[4]: Nothing to be done for 'check-am'.
 make[4]: Leaving directory '[...]/tschwinge/W._C._Handy.build/bfd'
 make[3]: Leaving directory '[...]/tschwinge/W._C._Handy.build/bfd'
 make[2]: Leaving directory '[...]/tschwinge/W._C._Handy.build/bfd'
 make[2]: Entering directory '[...]/tschwinge/W._C._Handy.build/opcodes'
 Making check in .
 make[3]: Entering directory '[...]/tschwinge/W._C._Handy.build/opcodes'
-make[3]: Nothing to be done for 'check-am'.
 make[3]: Leaving directory '[...]/tschwinge/W._C._Handy.build/opcodes'
 Making check in po
 make[3]: Entering directory '[...]/tschwinge/W._C._Handy.build/opcodes/po'
@@ -52,7 +50,7 @@ if /bin/dash -c "$runtest --version" > /dev/null 2>&1; then \
 else echo "WARNING: could not find \`runtest'" 1>&2; :;\
 fi
 WARNING: Couldn't find tool init file
-Test Run By thomas on Mon Nov  2 22:10:48 2015
+Test Run By thomas on Mon May 23 14:34:46 2016
 Native configuration is i686-pc-linux-gnu
 
 		=== binutils tests ===
@@ -134,7 +132,7 @@ if /bin/dash -c "$runtest --version" > /dev/null 2>&1; then \
 else echo "WARNING: could not find \`runtest'" 1>&2; :;\
 fi
 WARNING: Couldn't find tool init file
-Test Run By thomas on Mon Nov  2 22:10:56 2015
+Test Run By thomas on Mon May 23 14:34:50 2016
 Native configuration is i686-pc-linux-gnu
 
 		=== gas tests ===
@@ -278,7 +276,7 @@ Running [...]/tschwinge/W._C._Handy/gas/testsuite/gas/z8k/z8k.exp ...
 
 		=== gas Summary ===
 
-# of expected passes		506
+# of expected passes		507
 ../as-new 2.25.51.20150819
 
 make[4]: Leaving directory '[...]/tschwinge/W._C._Handy.build/gas'
@@ -317,7 +315,6 @@ make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/bfd/po'
 make[4]: Nothing to be done for 'all'.
 make[4]: Leaving directory '[...]/tschwinge/W._C._Handy.build/bfd/po'
 make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/bfd'
-make[4]: Nothing to be done for 'all-am'.
 make[4]: Leaving directory '[...]/tschwinge/W._C._Handy.build/bfd'
 make[3]: Leaving directory '[...]/tschwinge/W._C._Handy.build/bfd'
 make[2]: Leaving directory '[...]/tschwinge/W._C._Handy.build/bfd'
@@ -326,7 +323,6 @@ make  all-recursive
 make[3]: Entering directory '[...]/tschwinge/W._C._Handy.build/opcodes'
 Making all in .
 make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/opcodes'
-make[4]: Nothing to be done for 'all-am'.
 make[4]: Leaving directory '[...]/tschwinge/W._C._Handy.build/opcodes'
 Making all in po
 make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/opcodes/po'
@@ -346,7 +342,6 @@ make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/gas/po'
 make[4]: Nothing to be done for 'all'.
 make[4]: Leaving directory '[...]/tschwinge/W._C._Handy.build/gas/po'
 make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/gas'
-make[4]: Nothing to be done for 'all-am'.
 make[4]: Leaving directory '[...]/tschwinge/W._C._Handy.build/gas'
 make[3]: Leaving directory '[...]/tschwinge/W._C._Handy.build/gas'
 make[2]: Leaving directory '[...]/tschwinge/W._C._Handy.build/gas'
@@ -373,7 +368,6 @@ make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/binutils/po'
 make[4]: Nothing to be done for 'all'.
 make[4]: Leaving directory '[...]/tschwinge/W._C._Handy.build/binutils/po'
 make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/binutils'
-make[4]: Nothing to be done for 'all-am'.
 make[4]: Leaving directory '[...]/tschwinge/W._C._Handy.build/binutils'
 make[3]: Leaving directory '[...]/tschwinge/W._C._Handy.build/binutils'
 make[2]: Leaving directory '[...]/tschwinge/W._C._Handy.build/binutils'
@@ -1766,7 +1760,6 @@ make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/gprof/po'
 make[4]: Nothing to be done for 'check'.
 make[4]: Leaving directory '[...]/tschwinge/W._C._Handy.build/gprof/po'
 make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/gprof'
-make[4]: Nothing to be done for 'check-am'.
 make[4]: Leaving directory '[...]/tschwinge/W._C._Handy.build/gprof'
 make[3]: Leaving directory '[...]/tschwinge/W._C._Handy.build/gprof'
 make[2]: Leaving directory '[...]/tschwinge/W._C._Handy.build/gprof'
@@ -1801,7 +1794,7 @@ if /bin/dash -c "$runtest --version" > /dev/null 2>&1; then \
 else echo "WARNING: could not find \`runtest'" 1>&2; :;\
 fi
 WARNING: Couldn't find tool init file
-Test Run By thomas on Mon Nov  2 22:15:37 2015
+Test Run By thomas on Mon May 23 14:37:14 2016
 Native configuration is i686-pc-linux-gnu
 
 		=== ld tests ===
@@ -1962,7 +1955,7 @@ Running [...]/tschwinge/W._C._Handy/ld/testsuite/ld-xtensa/xtensa.exp ...
 
 		=== ld Summary ===
 
-# of expected passes		1142
+# of expected passes		1164
 # of expected failures		4
 # of untested testcases		6
 # of unsupported tests		8
@@ -2069,7 +2062,7 @@ Making a new config file...
 make check-single
 make[4]: Entering directory '[...]/tschwinge/W._C._Handy.build/gdb/testsuite'
 rootme=`pwd`; export rootme; srcdir=../../../W._C._Handy/gdb/testsuite ; export srcdir ; EXPECT=`if [ "${READ1}" != "" ] ; then echo ${rootme}/expect-read1; elif [ -f ${rootme}/../../expect/expect ] ; then echo ${rootme}/../../expect/expect ; else echo expect ; fi` ; export EXPECT ; EXEEXT= ; export EXEEXT ; LD_LIBRARY_PATH=$rootme/../../expect:$rootme/../../libstdc++:$rootme/../../tk/unix:$rootme/../../tcl/unix:$rootme/../../bfd:$rootme/../../opcodes:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; if [ -f ${rootme}/../../expect/expect ] ; then TCL_LIBRARY=${srcdir}/../../tcl/library ; export TCL_LIBRARY ; fi ; runtest  
-Test Run By thomas on Mon Nov  2 22:20:12 2015
+Test Run By thomas on Mon May 23 14:38:28 2016
 Native configuration is i686-pc-linux-gnu
 
 		=== gdb tests ===
@@ -2490,8 +2483,6 @@ ERROR OCCURED: : spawn id exp8 not open
     ("uplevel" body line 1)
     invoked from within
 "uplevel $body" NONE : spawn id exp8 not openWARNING: remote_expect statement without a default case?!
-FAIL: gdb.base/ending-run.exp: step out of main
-FAIL: gdb.base/ending-run.exp: step to end of run
 Running ../../../W._C._Handy/gdb/testsuite/gdb.base/enum_cond.exp ...
 Running ../../../W._C._Handy/gdb/testsuite/gdb.base/enumval.exp ...
 Running ../../../W._C._Handy/gdb/testsuite/gdb.base/environ.exp ...
@@ -2662,8 +2653,6 @@ ERROR OCCURED: : spawn id exp8 not open
     ("uplevel" body line 1)
     invoked from within
 "uplevel $body" NONE : spawn id exp8 not openFAIL: gdb.base/multi-forks.exp: run to exit 2 (timeout)
-FAIL: gdb.base/multi-forks.exp: info breakpoints (timeout)
-ERROR: breakpoints not deleted
 ERROR OCCURED: : spawn id exp8 not open
     while executing
 "expect {
@@ -2673,7 +2662,8 @@ ERROR OCCURED: : spawn id exp8 not open
 		if {[info exists e..."
     ("uplevel" body line 1)
     invoked from within
-"uplevel $body" NONE : spawn id exp8 not openRunning ../../../W._C._Handy/gdb/testsuite/gdb.base/multi-line-starts-subshell.exp ...
+"uplevel $body" NONE : spawn id exp8 not openFAIL: gdb.base/multi-forks.exp: run to exit 2 (timeout)
+Running ../../../W._C._Handy/gdb/testsuite/gdb.base/multi-line-starts-subshell.exp ...
 Running ../../../W._C._Handy/gdb/testsuite/gdb.base/nextoverexit.exp ...
 Running ../../../W._C._Handy/gdb/testsuite/gdb.base/nodebug.exp ...
 Running ../../../W._C._Handy/gdb/testsuite/gdb.base/nofield.exp ...
@@ -2775,7 +2765,6 @@ ERROR OCCURED: : spawn id exp8 not open
     ("uplevel" body line 1)
     invoked from within
 "uplevel $body" NONE : spawn id exp8 not openWARNING: remote_expect statement without a default case?!
-FAIL: gdb.base/shlib-call.exp: print g
 ERROR OCCURED: : spawn id exp8 not open
     while executing
 "expect {
@@ -3104,8 +3093,6 @@ ERROR OCCURED: : spawn id exp8 not open
     ("uplevel" body line 1)
     invoked from within
 "uplevel $body" NONE : spawn id exp8 not openWARNING: remote_expect statement without a default case?!
-FAIL: gdb.base/varargs.exp: print find_max_float_real(4, fc1, fc2, fc3, fc4)
-FAIL: gdb.base/varargs.exp: print find_max_double_real(4, dc1, dc2, dc3, dc4)
 Running ../../../W._C._Handy/gdb/testsuite/gdb.base/vdso-warning.exp ...
 Running ../../../W._C._Handy/gdb/testsuite/gdb.base/vla-datatypes.exp ...
 Running ../../../W._C._Handy/gdb/testsuite/gdb.base/vla-ptr.exp ...
@@ -3470,7 +3457,6 @@ ERROR OCCURED: : spawn id exp8 not open
     ("uplevel" body line 1)
     invoked from within
 "uplevel $body" NONE : spawn id exp8 not openWARNING: remote_expect statement without a default case?!
-FAIL: gdb.gdb/complaints.exp: list has one entry
 ERROR OCCURED: : spawn id exp8 not open
     while executing
 "expect {
@@ -3973,6 +3959,17 @@ Running ../../../W._C._Handy/gdb/testsuite/gdb.threads/manythreads.exp ...
 Running ../../../W._C._Handy/gdb/testsuite/gdb.threads/multi-create-ns-info-thr.exp ...
 Running ../../../W._C._Handy/gdb/testsuite/gdb.threads/multi-create.exp ...
 Running ../../../W._C._Handy/gdb/testsuite/gdb.threads/multiple-step-overs.exp ...
+FAIL: gdb.threads/multiple-step-overs.exp: displaced=on: step: setup: continue to breakpoint: run to breakpoint in thread 3
+FAIL: gdb.threads/multiple-step-overs.exp: displaced=on: step: setup: unbreak loop in thread 3
+FAIL: gdb.threads/multiple-step-overs.exp: displaced=on: step: step
+FAIL: gdb.threads/multiple-step-overs.exp: displaced=on: continue: setup: continue to breakpoint: run to breakpoint in thread 2
+FAIL: gdb.threads/multiple-step-overs.exp: displaced=on: continue: setup: unbreak loop in thread 2
+FAIL: gdb.threads/multiple-step-overs.exp: displaced=on: continue: continue
+FAIL: gdb.threads/multiple-step-overs.exp: displaced=on: signal thr2: setup: continue to breakpoint: run to breakpoint in thread 3
+FAIL: gdb.threads/multiple-step-overs.exp: displaced=on: signal thr2: setup: unbreak loop in thread 3
+FAIL: gdb.threads/multiple-step-overs.exp: displaced=on: signal thr2: continue to sigusr1_handler
+FAIL: gdb.threads/multiple-step-overs.exp: displaced=on: signal thr3: setup: continue to breakpoint: run to breakpoint in thread 3
+FAIL: gdb.threads/multiple-step-overs.exp: displaced=on: signal thr3: setup: unbreak loop in thread 3
 Running ../../../W._C._Handy/gdb/testsuite/gdb.threads/next-bp-other-thread.exp ...
 Running ../../../W._C._Handy/gdb/testsuite/gdb.threads/next-while-other-thread-longjmps.exp ...
 Running ../../../W._C._Handy/gdb/testsuite/gdb.threads/no-unwaited-for-left.exp ...
@@ -4075,15 +4072,15 @@ Running ../../../W._C._Handy/gdb/testsuite/gdb.xml/tdesc-xinclude.exp ...
 
 		=== gdb Summary ===
 
-# of expected passes		34125
-# of unexpected failures	157
+# of expected passes		34150
+# of unexpected failures	162
 # of unexpected successes	1
-# of expected failures		64
+# of expected failures		68
 # of unknown successes		1
-# of known failures		63
-# of unresolved testcases	4
-# of untested testcases		41
-# of unsupported tests		67
+# of known failures		64
+# of unresolved testcases	3
+# of untested testcases		40
+# of unsupported tests		66
 [...]/tschwinge/W._C._Handy.build/gdb/testsuite/../../gdb/gdb version  7.10.50.20150819-cvs -nw -nx -data-directory [...]/tschwinge/W._C._Handy.build/gdb/testsuite/../data-directory 
 
 Makefile:196: recipe for target 'check-single' failed
